language: node_js
node_js:
  "12"
env:
  - "DATABASE_URL=postgresql://localhost:5432/dididata"

before_script:
  - psql -c 'create database dididata;' -U postgres
  - psql -U postgres -d dididata -a -f sql/tables.sql
services:
  - postgresql